"""Chnage users table

Revision ID: 303177e00c81
Revises: bc2f04bf1419
Create Date: 2025-09-20 22:59:20.980603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303177e00c81'
down_revision = 'bc2f04bf1419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
